# Generated by Django 4.2.4 on 2023-08-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_booktag_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(null=True),
        ),
    ]
